<?xml version="1.0"?>
<!--
Copyright (c) 2013, Goncalo Cabrita/ISR University of Coimbra
Copyright (c) 2012, Ryan Gariepy/Clearpath Robotics
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Clearpath Robotics nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This program contains the description of the HRATC2015 Husky robot based on the original Clearpath 
Husky A200 file and modified by the ISR University of Coimbra
-->

<robot 

    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
    xmlns:xacro="http://ros.org/wiki/xacro" name="husky">
       
    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find hratc2015_dataset)/urdf/husky_parts/materials.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/husky_parts/wheel.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/husky_parts/parts.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/husky_bridge.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/tim55x.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/alfa_tube2h.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/pointgrey_flea3.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/gps_antenna.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/tilt.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/mti.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/arm/fsr_husky_arm.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/front_cover.urdf.xacro" />
    <xacro:include filename="$(find hratc2015_dataset)/urdf/fsr_husky_parts/top_cover.urdf.xacro" />

    <!-- PROPERTY LIST -->
    <!--All units in m-kg-s-radians unit system -->
    <property name="M_PI" value="3.1415926535897931" />

    <!-- Main Body-base-->
    <!-- Location of com : center of mass -->
    <property name="base_x_com" value="-0.08748000" />
    <property name="base_y_com" value="-0.00085000" />
    <property name="base_z_com" value="0.09947000" />

    <!-- Size of the base-->
    <property name="base_x_size" value="0.98740000" /> 
    <property name="base_y_size" value="0.57090000" /> 
    <property name="base_z_size" value="0.24750000" />

    <!--Weight of the base-->
    <property name="base_mass" value="3.345489000" /> <!-- in kg-->

    <!--Inertial values for the base at center of mass, aligned with coordinate system. Units are kg*m^2-->
    <property name="base_ixx_com_cs" value="6.0216370" />
    <property name="base_ixy_com_cs" value="0.0" />
    <property name="base_ixz_com_cs" value="0.0" />
    <property name="base_iyy_com_cs" value="17.3859574" />
    <property name="base_iyz_com_cs" value="0.0" />
    <property name="base_izz_com_cs" value="20.2955229" />

    <!-- BASE-FOOTPRINT -->
    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
    <link name="base_footprint">
        <!--<inertial>
            <mass value="0.0001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0" 
                izz="0.0001" />
	      </inertial>-->

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>

    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${wheel_x_size/2 - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>

    <!-- BASE-LINK -->
    <!--Actual body/chassis of the robot-->
    <link name="base_link">
        <inertial>
            <mass value="${base_mass}" />
            <!--This is the pose of the inertial reference frame, relative to the link reference frame. The origin of the inertial reference frame needs to be at the center of gravity. The axes of the inertial reference frame do not need to be aligned with the principal axes of the inertia.-->
            <origin xyz="${base_x_com} ${base_y_com} ${base_z_com}" />
            <!--The 3x3 rotational inertia matrix. Because the rotational inertia matrix is symmetric, only 6 above-diagonal elements of this matrix are specified here, using the attributes ixx, ixy, ixz, iyy, iyz, izz.-->
            <inertia ixx="${base_ixx_com_cs}" ixy="${base_ixy_com_cs}" ixz="${base_ixz_com_cs}"
                iyy="${base_iyy_com_cs}" iyz="${base_iyz_com_cs}" izz="${base_izz_com_cs}" /> 
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
		<mesh filename="package://hratc2015_dataset/models/husky_parts/base_link.stl" />
            </geometry>
            <material name="Black" />
        </visual>
    
		<collision>
			<origin xyz="0 0 ${wheel_x_size/2 - base_z_origin_to_wheel_origin - 0.02}" rpy="0 0 0 " />
			<geometry>
				<box size = "${base_x_size+0.02} ${base_y_size} ${base_z_size + 0.02}"/> <!--making it slightly bigger in x and z direction-->
			</geometry>
		</collision>     
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/FlatBlack</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- WHEEL macros -->
	<husky_wheel fb="back" lr="left" parent="base_link" translateX="-1" translateY="1" flipY="-1"/>
	<husky_wheel fb="back" lr="right" parent="base_link" translateX="-1" translateY="-1" flipY="-1"/>
	<husky_wheel fb="front" lr="left" parent="base_link" translateX="1" translateY="1" flipY="-1"/>
	<husky_wheel fb="front" lr="right" parent="base_link" translateX="1" translateY="-1" flipY="-1"/>

    <!-- DECORATIONS -->
    <!-- Top Plate -->
    <husky_part parent="base_footprint" name="top_plate" mesh="top_plate" 
          colour="Yellow"
          translateX="0.0" translateY="0.0" translateZ="${wheel_x_size/2 - base_z_origin_to_wheel_origin}" 
          rotateX="0.0" rotateY="0.0" rotateZ="0.0"/>
    <gazebo reference="base_footprint_top_plate_part">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- User Rail -->
    <husky_part parent="base_footprint" name="user_rail" mesh="user_rail"
          colour="DarkGray"
          translateX="0.272" translateY="0.0" translateZ="${0.245 + wheel_x_size/2 - base_z_origin_to_wheel_origin}" 
          rotateX="0.0" rotateY="0.0" rotateZ="0.0"/>
    <gazebo reference="base_footprint_user_rail_part">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Bumpers -->
    <husky_part parent="base_footprint" name="rear_bumper" mesh="bumper"
          colour="DarkGray"
          translateX="-0.48" translateY="0.0" translateZ="${0.091 + wheel_x_size/2 - base_z_origin_to_wheel_origin}" 
          rotateX="0.0" rotateY="0.0" rotateZ="3.14"/>
    <gazebo reference="base_footprint_rear_bumper_part">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <gazebo>
	<plugin name="husky_diff_controller" filename="libhusky_gazebo_plugins.so">
	    <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <backLeftJoint>joint_back_left_wheel</backLeftJoint>
            <backRightJoint>joint_back_right_wheel</backRightJoint>
            <frontLeftJoint>joint_front_left_wheel</frontLeftJoint>
            <frontRightJoint>joint_front_right_wheel</frontRightJoint>
            <wheelSeparation>${base_y_size}</wheelSeparation>
            <wheelDiameter>${wheel_x_size}</wheelDiameter>
            <torque>35</torque>	
        </plugin>
    </gazebo>

    <!-- FSR Husky Stuff -->

    <!-- BRIDGE macros -->
    <husky_bridge parent="base_link" x="-0.27" y="0" z="${base_z_size}" rx="0" ry="0" rz="0" />

    <!-- Top cover macros -->
    <top_cover parent="base_footprint" x="-0.18" y="0" z="${base_z_size}" rx="0" ry="0" rz="0" />

    <!-- Front cover macros -->
    <front_cover parent="base_footprint" x="0" y="0" z="${base_z_size}" rx="0" ry="0" rz="0" />

    <!-- MTi macro -->
    <mti parent="top_cover" x="0.2295" y="0.0" z="0.157" rx="0" ry="0" rz="0" />

    <!-- CAMERA macros -->
    <pointgrey_flea3 prefix="right" parent="husky_bridge" base_offset="-0.145" camera_offset="-0.00" camera_r="0" camera_p="0" camera_y="0" />
    <pointgrey_flea3 prefix="left" parent="husky_bridge" base_offset="0.145" camera_offset="0.00" camera_r="0" camera_p="0" camera_y="0" />

    <!-- Tilt macro -->
    <tilt parent="husky_bridge" x="0.0" y="-0.00601" z="-0.647711" rx="0" ry="0" rz="${M_PI/2}" />

    <!-- TIM macro -->
    <tim_55x parent="tilt_link" x="0.0" y="0.0" z="0.0" rx="0" ry="0" rz="0" />

    <!-- GPS macro -->
    <gps_antenna parent="husky_bridge" x="0" y="-0.07" z="0.0" rx="0" ry="0" rz="0" />

    <!-- WiFi Antenna -->
    <alfa_tube2h parent="husky_bridge" x="-0.21" y="0.17" z="-0.38" rx="0" ry="0" rz="0" />

    <!-- FSR Husky De-mining Arm -->
    <fsr_husky_arm parent="base_link" x="0.0" y="0.0" z="0.0" rx="0" ry="0" rz="${M_PI/2}" />
    
    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
	<!--<robotNamespace>/husky</robotNamespace>-->
      </plugin>
    </gazebo>
  
</robot>
